[package]
name = "power_grep"
version = "0.1.0"
authors = ["Steffen Gerdes <sge@thepeaklab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
